included:
  - Sources
  - Tests
  - Package.swift

excluded:
  - .build
  - .local
  - dist

opt_in_rules:
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - modifier_order
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

analyzer_rules: []

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - large_tuple
  - opening_brace
  - trailing_whitespace
  - type_body_length

line_length:
  warning: 160
  error: 220
  ignores_comments: true
  ignores_urls: true

identifier_name:
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
    - lhs
    - rhs

reporter: "xcode"
